services:
  #webadm:
  #  restart: always
  #  platform: linux/amd64
  #  image: rcdevs/webadm:2.3.22
  #  #tty: true
  #  #entrypoint:
  #  #  - /bin/bash
  #  volumes:
  #    - ./webadm/:/opt/docker/
  #  ports:
  #    - 8080:8080
  #    - 443:443
  otp:
    build:
      context: ./
      dockerfile: otp.Dockerfile
    ports:
      - 8080:8080
  ldap:
    image: ghcr.io/widespot/ldap:v0.1.1-2.6.8-deb12.7
    ports:
      - 389:389
      - 636:636
    #environment:
    #  OLC_SUFFIX: ''
    volumes:
      - ./seed.ldif:/seed/seed.ldif
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: webadm
      POSTGRES_DB: webadm
